# make train, test dataset

In [149]:
# import library
import pandas as pd
import numpy as np

auth_cols = ["time", "suser_do", "duser_do", "scom", "dcom", "a_t", "logon_type", "a_ot", "s/f"]


df_auth_cols = ["time", "s_user", "s_domain",  "d_user","d_domain", "scom", "dcom", "a_t", "logon_type", "a_ot", "s/f"]


In [150]:
# load data

df = pd.read_csv("/home/shkim/testfolder/abnoral-detection-lanl2015/abnoral-detection-lanl2015/df_auth.csv")
df_attack = pd.read_csv("/home/shkim/testfolder/abnoral-detection-lanl2015/abnoral-detection-lanl2015/attack1.csv")



In [153]:
df.drop("Unnamed: 0", axis = 1, inplace = True)

In [151]:
df_attack

Unnamed: 0     time s_user s_domain d_user d_domain    scom   dcom   a_t  \
0             0   150885   U620     DOM1   U620     DOM1  C17693  C1003  NTLM   
1             1   151036   U748     DOM1   U748     DOM1  C17693   C305  NTLM   
2             2   151648   U748     DOM1   U748     DOM1  C17693   C728  NTLM   
3             3   151993  U6115     DOM1  U6115     DOM1  C17693  C1173  NTLM   
4             4   153792   U636     DOM1   U636     DOM1  C17693   C294  NTLM   
..          ...      ...    ...      ...    ...      ...     ...    ...   ...   
711         738  2551583   U737     DOM1   U737     DOM1  C19932   C108  NTLM   
712         739  2552687  U9263     DOM1  U9263     DOM1  C17693   C828  NTLM   
713         740  2552687  U9263     DOM1  U9263     DOM1  C17693   C828  NTLM   
714         747  2552687   U655     DOM1   U655     DOM1  C17693   C828  NTLM   
715         752  2557047   U737     DOM1   U737     DOM1  C19932   C108  NTLM   

    logon_type   a_ot      s/f  
0      Network  LogOn  Success  
1      Network  LogOn  Success  
2      Network  LogOn  Success  
3      Network  LogOn  Success  
4      Network  LogOn  Success  
..         ...    ...      ...  
711    Network  LogOn  Success  
712    Network  LogOn     Fail  
713    Network  LogOn  Success  
714    Network  LogOn  Success  
715    Network  LogOn  Success  

[716 rows x 12 columns]

In [154]:
df = df.iloc[:4284]

In [155]:
df["positive"] = 0
df_attack["positive"] = 1

In [159]:
# "\n" 제거
df["s/f"] = df["s/f"].str[:-1]


In [160]:
df = pd.concat([df, df_attack])

In [161]:
df

time           s_user s_domain           d_user d_domain    scom  \
0    3631772              U13     DOM1              U13     DOM1    C368   
1    3901683            U7971   C25126            U7971   C25126  C25126   
2     512998            C6522     DOM1            C6522     DOM1   C6522   
3     177835              U66     DOM1              U66     DOM1   C1673   
4     164787  NETWORK SERVICE    C4541  NETWORK SERVICE    C4541   C4541   
..       ...              ...      ...              ...      ...     ...   
711  2551583             U737     DOM1             U737     DOM1  C19932   
712  2552687            U9263     DOM1            U9263     DOM1  C17693   
713  2552687            U9263     DOM1            U9263     DOM1  C17693   
714  2552687             U655     DOM1             U655     DOM1  C17693   
715  2557047             U737     DOM1             U737     DOM1  C19932   

      dcom        a_t logon_type   a_ot      s/f  positive  
0    C1065   Kerberos    Network  LogOn  Success         0  
1    C2951       NTLM    Network  LogOn     Fail         0  
2     C586   Kerberos    Network  LogOn  Success         0  
3    C1673   Kerberos    Network  LogOn  Success         0  
4    C4541  Negotiate    Service  LogOn  Success         0  
..     ...        ...        ...    ...      ...       ...  
711   C108       NTLM    Network  LogOn  Success         1  
712   C828       NTLM    Network  LogOn     Fail         1  
713   C828       NTLM    Network  LogOn  Success         1  
714   C828       NTLM    Network  LogOn  Success         1  
715   C108       NTLM    Network  LogOn  Success         1  

[5000 rows x 12 columns]

In [162]:
df = df.drop_duplicates(df_auth_cols, keep = 'last')

In [191]:
df

time           s_user s_domain           d_user d_domain    scom  \
0    3631772              U13     DOM1              U13     DOM1    C368   
1    3901683            U7971   C25126            U7971   C25126  C25126   
2     512998            C6522     DOM1            C6522     DOM1   C6522   
3     177835              U66     DOM1              U66     DOM1   C1673   
4     164787  NETWORK SERVICE    C4541  NETWORK SERVICE    C4541   C4541   
..       ...              ...      ...              ...      ...     ...   
711  2551583             U737     DOM1             U737     DOM1  C19932   
712  2552687            U9263     DOM1            U9263     DOM1  C17693   
713  2552687            U9263     DOM1            U9263     DOM1  C17693   
714  2552687             U655     DOM1             U655     DOM1  C17693   
715  2557047             U737     DOM1             U737     DOM1  C19932   

      dcom        a_t logon_type   a_ot      s/f  positive  frequency  
0    C1065   Kerberos    Network  LogOn  Success         0          1  
1    C2951       NTLM    Network  LogOn     Fail         0          1  
2     C586   Kerberos    Network  LogOn  Success         0          1  
3    C1673   Kerberos    Network  LogOn  Success         0          1  
4    C4541  Negotiate    Service  LogOn  Success         0          1  
..     ...        ...        ...    ...      ...       ...        ...  
711   C108       NTLM    Network  LogOn  Success         1          1  
712   C828       NTLM    Network  LogOn     Fail         1          1  
713   C828       NTLM    Network  LogOn  Success         1          1  
714   C828       NTLM    Network  LogOn  Success         1          1  
715   C108       NTLM    Network  LogOn  Success         1          1  

[5000 rows x 13 columns]

In [164]:
g_header =  [ "s_user", "s_domain",  "d_user","d_domain", "scom", "dcom", "a_t", "logon_type", "a_ot", "s/f"]
df["frequency"] = 1

In [256]:
from sklearn.model_selection import train_test_split

X=df.drop("positive", axis=1)
Y=df['positive']

In [257]:
x_train, x_test, y_train, y_test  = train_test_split(X, Y,test_size=0.3, stratify=Y, random_state=123)


In [258]:
x_train = x_train.reset_index()
x_test = x_test.reset_index()

In [259]:
x_train.drop("index", axis = 1,inplace=True)
x_test.drop("index", axis = 1, inplace=True)

In [260]:
y_train = y_train.reset_index()
y_test = y_test.reset_index()

In [261]:
y_train.drop("index", axis = 1,inplace=True)
y_test.drop("index", axis = 1, inplace=True)

In [262]:
y_test[y_test["positive"] == 1]

#비정상행위 215개

positive
4            1
5            1
9            1
25           1
30           1
...        ...
1465         1
1466         1
1469         1
1486         1
1495         1

[215 rows x 1 columns]

In [263]:
x_train_group = x_train.groupby(g_header).transform('count')
x_test_group = x_test.groupby(g_header).transform('count')

In [264]:
x_train["frequency"] = x_train_group["frequency"]
x_test["frequency"] = x_test_group["frequency"]


# one-hot-vector

In [265]:
encoding_h = ["s_user", "d_user", "a_t", "logon_type", "frequency"]

In [247]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit(x_train[encoding_h])

/home/shkim/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [171]:
x_train_encoding = ohe.transform(x_train[encoding_h])

In [172]:
x_test_encoding = ohe.transform(x_test[encoding_h])
# train데이터가 test의 카테고리를 다 소화하지 못함

ValueError: Found unknown categories ['U3992', 'C9', 'C14809', 'C16436', 'U9545', 'U701', 'U9636', 'C2820', 'U3516', 'U384', 'C14975', 'C17297', 'U720', 'U3206', 'C14328', 'C14423', 'C12251', 'C26491', 'C11364', 'C20367', 'C18863', 'C4856', 'U5476', 'C2324', 'C16299', 'C6395', 'C7852', 'U6615', 'C3038', 'U8717', 'C19193', 'C363', 'C122', 'U1797', 'C12218', 'C1770', 'C9976', 'C12956', 'C2891', 'U2338', 'U68', 'C13128', 'U9650', 'C6832', 'C19522', 'C2645', 'U4090', 'U3775', 'C1418', 'C12937', 'U1159', 'C478', 'C22507', 'C8200', 'C6544', 'C22008', 'C7612', 'C22088', 'C2863', 'C8996', 'U930', 'U9344', 'U27', 'C23953', 'U1358', 'C6937', 'C241', 'C2077', 'C1488', 'U4858', 'U4915', 'C16557', 'U1900', 'U1999', 'C1471', 'U7757', 'U2134', 'C21108', 'C2203', 'C10845', 'U2430', 'C2602', 'U545', 'C4028', 'U7398', 'C1906', 'U980', 'C18383', 'U3793', 'C6986', 'U9720', 'C4349', 'C9373', 'C4581', 'C804', 'C21490', 'C7780', 'U9128', 'U10222', 'U472', 'C3424', 'U1341', 'U2665', 'C24020', 'C20567', 'U6371', 'C11904', 'C14083', 'C16939', 'C1201', 'C1501', 'C10148', 'C314', 'U9441', 'U2423', 'C15924', 'C23018', 'C5123', 'C1912', 'C15292', 'C19322', 'U9346', 'U234', 'C15477', 'U7405', 'U3948', 'C21833', 'C7158', 'C15013', 'C2117', 'C3042', 'C6135', 'C963', 'U8869', 'C13958', 'U3511', 'C10933', 'C3719', 'C13', 'C9978', 'C1187', 'C16328', 'C11775', 'C18597', 'C13194', 'U1369', 'U9358', 'U5644', 'U891', 'U4576', 'C3003', 'U3692', 'C22873', 'C9825', 'C19112', 'C14581', 'C9851', 'C16512', 'C6474', 'C430', 'C15902', 'C3973', 'C13646', 'U831', 'U7528', 'C15266', 'C3921', 'U4164', 'C1658', 'C14903', 'C2195', 'C13674', 'U849', 'C7483', 'C652', 'C13705', 'U6215', 'C8908', 'C19852', 'C1777', 'C1030', 'C3611', 'C11180', 'C2313', 'C3720', 'C10287', 'C2396', 'C5489', 'U2654', 'U3476', 'C9270', 'C2039', 'C3274', 'C11294', 'U1213', 'U6560', 'C2433', 'C22048', 'U7717', 'U4868', 'C7354', 'U8937', 'C16038', 'C10056', 'U8480', 'C16356', 'U7574', 'C11496', 'U8406', 'C3586', 'U4230', 'C8437', 'C2186', 'C28', 'C6328', 'U2798', 'C16218', 'C1788', 'C8021', 'U3274', 'C24392', 'C19789', 'C3363', 'C5', 'C13328', 'U2352', 'C11059', 'C1552', 'C9400', 'U3603', 'C4909', 'C4820', 'C15984', 'U2602', 'C7065', 'C17370', 'C10852', 'C2633', 'U513', 'C1871', 'C6283', 'C20546', 'C4156', 'C10049', 'U5965', 'C3427', 'U4', 'U5298', 'U7637', 'C35', 'C12036', 'U9175', 'C17796', 'U5532', 'C19881', 'C14544', 'C12705', 'U7732', 'U9203', 'U9393', 'C16060', 'C9485', 'C21115', 'C16439', 'C3309', 'C925', 'C422', 'C7854', 'C14496', 'C4355', 'U4454', 'U372', 'C365', 'C16524', 'U5516', 'C22064', 'C2786', 'C1431', 'C2380', 'C14102', 'C1437', 'C6681', 'C2943', 'C1439', 'C10317', 'C2219', 'U4391', 'U7368', 'U9541', 'C2660', 'C4223', 'C3468', 'C7662', 'C14500', 'U3277', 'C17976', 'C589', 'U8417', 'C2103', 'U5778', 'C19231', 'C15010', 'U20', 'C8350', 'C154', 'C23084', 'C10931', 'C13185', 'C2344', 'C22509', 'C7980', 'C7448', 'C1321', 'C12562', 'C2702', 'U3241', 'U4478', 'C350', 'C7063', 'C10138', 'C23921', 'C24450', 'U5813', 'C17596', 'C16587', 'C9827', 'C12490', 'C5295', 'C19274', 'C3662', 'C433', 'C381', 'U2848', 'C17448', 'U3250', 'U5437', 'U158', 'C25914', 'C1596', 'C15172', 'C453', 'U367', 'U4223', 'C8962', 'C4578', 'U2031', 'C11029', 'C11244', 'C1767', 'C14601', 'C3841', 'C15715', 'C3873', 'C20707', 'U7221', 'U6236', 'C1928', 'C22944', 'U2678', 'U7001', 'C182', 'U3782', 'C22758', 'C3660', 'C4118', 'C13757', 'U5610', 'C3241', 'C832', 'C978', 'C1763', 'C10939', 'U313', 'C712', 'U8661', 'U4604', 'C5974', 'C18238', 'U2326', 'U5440', 'U333', 'C1827', 'U1401', 'U6173', 'U654', 'U7128', 'C18343', 'U8728', 'C1745', 'C6014', 'C5641', 'C18163', 'U8696', 'U2726', 'C2254', 'C15164', 'C16656', 'C12089', 'C1420', 'U8082', 'U1394', 'U2884', 'C8159', 'C7930', 'C4941', 'C634', 'U70', 'U890', 'C12900', 'C8361', 'U7159', 'U5915', 'U3908', 'U6110', 'C5308', 'C9849', 'C12576', 'C19050', 'C12067', 'C15495', 'C2724', 'C526', 'C5336', 'C7217', 'C3960', 'C1998', 'C3384', 'C19505', 'C9347', 'U41', 'C8814', 'C3055', 'C4749', 'C4939', 'C5208', 'C3173', 'C3412', 'C12773', 'U3885', 'C7736', 'U10044', 'C16909', 'C15841', 'C1152', 'C8088', 'C10995', 'U2875', 'C13724', 'C14988', 'C11327', 'C6841', 'C2970', 'C2683', 'C19487', 'C13717', 'U2499', 'C3787', 'U910', 'C24014', 'U1907', 'C2827', 'U99', 'C7513', 'C1467', 'C23586', 'C7497', 'U7813', 'U9335', 'U2749', 'C4116', 'C2825', 'U8069', 'C17720', 'C11292', 'U3649', 'C9756', 'U3275', 'C25919', 'C10786', 'C5041', 'C3460', 'C1247', 'C6723', 'C2465', 'C15326', 'C791', 'U253', 'C6522', 'C23044', 'C24615', 'C1076', 'C4315', 'U5948', 'C20756', 'C4792', 'U8629', 'C7742', 'C16545', 'C22346', 'C2933', 'C15753', 'C14330', 'U3667', 'C9473', 'C24067', 'U9253', 'C20130', 'C16332', 'C3324', 'C4167', 'U6259', 'C17418', 'C19149', 'U2181', 'C7802', 'C10460', 'C6205', 'C789', 'U4260', 'C186', 'C13446', 'C17133', 'U3207', 'C10790', 'U4866', 'C16652', 'C5183', 'C8023', 'U881', 'U2489', 'U7474', 'C1857', 'C4513', 'U453', 'U4939', 'C3377', 'C19856', 'C626', 'U2248', 'U4180', 'U6483', 'C25421', 'U7969', 'C16243', 'U2510', 'C16930', 'C41', 'C1107', 'U1467', 'U101', 'C21785', 'C19509', 'C1356', 'C2350', 'C1273', 'U9750', 'C10223', 'C736', 'U9225', 'U2372', 'U1306', 'C12263', 'C5401', 'C1790', 'C2096', 'C21220', 'U4814', 'C1672', 'C15216', 'C2557', 'C2992', 'U9892', 'C1675', 'U1163', 'C13640', 'C9404', 'C7151', 'C23195', 'C24410', 'U3090', 'C17598', 'C20120', 'U8838', 'C801', 'C1921', 'C24145', 'U7614', 'C12055', 'C13923', 'C23673', 'C4670', 'C11924', 'C686', 'U6793', 'C10688', 'C11167', 'C11804', 'C22503', 'U2082', 'C2370', 'C9815', 'U5095', 'C22511', 'C11001', 'C68', 'C3667', 'C19863', 'C8761', 'C19016', 'U4984', 'C7637', 'C1476', 'U508', 'C10295', 'U903', 'C4310', 'U767', 'C1220', 'U5085', 'C15602', 'C2504', 'C19308', 'C545', 'C11516', 'C6377', 'C1952', 'C2092', 'C16312', 'C675', 'C19118', 'U11095', 'C17759', 'U2719', 'U1388', 'U5991', 'C714', 'C14132', 'U5856', 'C8789', 'C9481', 'C9908', 'C17168', 'C6008', 'C15873', 'C23403', 'C5576', 'U1824', 'C248', 'C9384', 'U3771', 'C543', 'U2563', 'C15648', 'C3965', 'C2021', 'C6039', 'C20220', 'C15339', 'U1789', 'C2317', 'C12318', 'U2804', 'U156', 'C9144', 'C15390', 'C2148', 'C17998', 'C9161', 'C17723', 'C2397', 'C19206', 'C3130', 'C7281', 'C20769', 'U6926', 'U4850', 'C17546', 'C13364', 'C5811', 'U4719', 'U4668', 'C22253', 'C2526', 'U7972', 'C12498', 'U9965', 'C3183', 'C4929', 'U7542', 'U8369', 'C1622', 'C8976', 'C957', 'C20427', 'C8005', 'C7790', 'C2499', 'C7144', 'U9058', 'C7277', 'C7162', 'C15462', 'C2058', 'U5463'] in column 0 during transform

In [266]:
from sklearn.preprocessing import OneHotEncoder
# 다 합쳐서 시작하기
X_all = pd.concat([x_train, x_test])
ohe = OneHotEncoder(sparse=False)
ohe.fit(X_all[encoding_h])
ohe.transform(X_all[encoding_h])

/home/shkim/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [267]:
len(ohe.categories_)

5

In [268]:
ohe_col = []
for col in ohe.categories_:
    ohe_col.extend(col.tolist())

In [269]:
ohe_df = pd.DataFrame(ohe.transform(X_all[encoding_h]), columns=ohe_col)

In [271]:
# 인덱스 맞추기

x_train.index
ohe_train = ohe_df.iloc[:x_train.shape[0]]
ohe_test = ohe_df.iloc[x_train.shape[0]:]
ohe_test.reset_index(drop=True, inplace=True)

In [272]:
x_train = pd.concat([x_train, ohe_train], axis = 1)
x_test = pd.concat([x_test, ohe_test], axis = 1)


In [273]:
x_train.shape, x_test.shape

((3500, 5420), (1500, 5420))

In [285]:
# 원래 범주형 데이터 삭제
x_train.drop(columns=encoding_h, inplace=True)
x_test.drop(columns=encoding_h, inplace=True)

KeyError: "['s_user' 'd_user' 'a_t' 'logon_type' 'frequency'] not found in axis"

array([0, 1])

# abnormal detection
# case 1: group header s_user, d_user, a_t, logon_type, frequency만 one-hot-encoding한경우
# case 2: 모든 데이터를 one-hot-encoding한 경우

In [286]:
df_auth_cols

['time',
 's_user',
 's_domain',
 'd_user',
 'd_domain',
 'scom',
 'dcom',
 'a_t',
 'logon_type',
 'a_ot',
 's/f']

# case 1

In [337]:
x_train_1 = x_train.drop(["time", "s_domain","d_domain", "scom","dcom", "a_ot", "s/f"], axis = 1)
x_test_1 =x_test.drop(["time", "s_domain","d_domain", "scom","dcom", "a_ot", "s/f"], axis = 1)

# Alogrithme kNN

In [279]:
#!pip install pyod

     |████████████████████████████████| 147 kB 6.7 MB/s eta 0:00:01
     |████████████████████████████████| 9.9 MB 6.3 MB/s eta 0:00:01
     |████████████████████████████████| 233 kB 6.9 MB/s eta 0:00:01
  Created wheel for pyod: filename=pyod-1.0.7-py3-none-any.whl size=181092 sha256=55c1a9e65cf64866014d3a804dbebe749c897ef83396e248315fc5dcdc74d562
  Stored in directory: /home/shkim/.cache/pip/wheels/f7/e2/c1/1c7fd8b261e72411f6509afb429c84532e40ddcd96074473f4
Successfully built pyod


In [280]:
from pyod.utils.example import visualize
from pyod.utils.data import evaluate_print
from pyod.utils.data import generate_data
from pyod.models.knn import KNN

In [281]:
# set parameter

algorithm='auto'
contamination=0.1
leaf_size=30
method='largest',
metric='minkowski'
metric_params=None
n_jobs=1
n_neighbors=100, 
p=2,
radius=1.0


In [290]:
# ▶ 모델 생성 및 학습
clf_name = 'KNN'
clf = KNN(algorithm='auto',contamination=0.1,leaf_size=30,method='largest',metric='minkowski',metric_params=None,n_jobs=1,n_neighbors=100, p=2,radius=1.0)
clf.fit(x_train_1)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=100, p=2,
  radius=1.0)

In [294]:
# ▶ Train set score
y_train_pred = clf.labels_
y_train_scores = clf.decision_scores_

In [295]:
# ▶ Test set score
y_test_pred = clf.predict(x_test_1)
y_test_scores = clf.decision_function(x_test_1)
#수행시간 1m 18.2s

In [296]:
# ▶ ROC : 분류기 성능
# ▶ precision @ n : 예측한 것 중에 정답률

print("On Training Data:")
evaluate_print(clf_name, y_train, y_train_scores)

print("\nOn Test Data:")
evaluate_print(clf_name, y_test, y_test_scores)

On Training Data:
KNN ROC:0.5955, precision @ rank n:0.3116

On Test Data:
KNN ROC:0.5312, precision @ rank n:0.2295


In [302]:
# confusion matrix
from sklearn.metrics import confusion_matrix

cf = confusion_matrix(y_train, y_train_pred)

In [306]:
from sklearn.metrics import classification_report

print(cf)
print(classification_report(y_train, y_train_pred))
print("-------------------------------------------------------")
print(classification_report(y_test, y_test_pred))

[[2986   13]
 [ 493    8]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92      2999
           1       0.38      0.02      0.03       501

    accuracy                           0.86      3500
   macro avg       0.62      0.51      0.48      3500
weighted avg       0.79      0.86      0.79      3500

-------------------------------------------------------
              precision    recall  f1-score   support

           0       0.86      1.00      0.92      1285
           1       1.00      0.03      0.05       215

    accuracy                           0.86      1500
   macro avg       0.93      0.51      0.49      1500
weighted avg       0.88      0.86      0.80      1500



# Algorithm LOF

In [308]:
import numpy as np
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor

In [311]:
x_train_1.columns = x_train_1.columns.astype(str)

In [319]:
# ▶ 모델 생성 및 예측
outlier = LocalOutlierFactor(algorithm='auto', contamination=0.1, leaf_size=30,
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=300, p=2)
y_predict = outlier.fit_predict(x_train_1)
x_train_1['outlier'] = y_predict
x_train_1

# 실행시간 1.4ch




ANONYMOUS LOGON  C10  C10010  C10012  C10031  C10049  C10056  C10065  \
0                 1.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1                 0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2                 0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3                 0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4                 0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...               ...  ...     ...     ...     ...     ...     ...     ...   
3495              0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3496              0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3497              0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3498              0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3499              0.0  0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      C10075  C1008  ...  6.0  7.0  8.0  9.0  10.0  11.0  17.0  23.0  nan  \
0        0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
1        0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
2        0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
3        0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
4        0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
...      ...    ...  ...  ...  ...  ...  ...   ...   ...   ...   ...  ...   
3495     0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
3496     0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
3497     0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
3498     0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   
3499     0.0    0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0  0.0   

      outlier  
0           1  
1           1  
2           1  
3           1  
4           1  
...       ...  
3495        1  
3496        1  
3497        1  
3498        1  
3499        1  

[3500 rows x 5409 columns]

In [324]:
# ▶ LOF 값 확인
# ▶ negative_outlier_factor_ : The opposite LOF of the training samples.
outlier.negative_outlier_factor_

array([-0.99672064, -0.99998153, -0.99983342, ..., -0.99998153,
       -0.99983342, -0.99983342])

In [322]:
# ▶ Train data Target ratio 확인
pd.Series(y_train["positive"]).value_counts(normalize=True)

0    0.856857
1    0.143143
Name: positive, dtype: float64

In [323]:
# ▶ Test data Target ratio 확인
pd.Series(y_test["positive"]).value_counts(normalize=True)

0    0.856667
1    0.143333
Name: positive, dtype: float64

In [328]:
# confusion matrix
from sklearn.metrics import confusion_matrix

cf = confusion_matrix(y_train,y_predict)

In [329]:

print(cf)
print(classification_report(y_train, y_train_pred))
print("-------------------------------------------------------")
print(classification_report(y_test, y_test_pred))

[[   0    0    0]
 [ 217    0 2782]
 [ 131    0  370]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92      2999
           1       0.38      0.02      0.03       501

    accuracy                           0.86      3500
   macro avg       0.62      0.51      0.48      3500
weighted avg       0.79      0.86      0.79      3500

-------------------------------------------------------
              precision    recall  f1-score   support

           0       0.86      1.00      0.92      1285
           1       1.00      0.03      0.05       215

    accuracy                           0.86      1500
   macro avg       0.93      0.51      0.49      1500
weighted avg       0.88      0.86      0.80      1500



# Algorithm ocsvm

In [339]:
x_train_1.columns = x_train_1.columns.astype(str)
x_test_1.columns = x_test_1.columns.astype(str)

In [330]:
import matplotlib.pyplot as plt
import matplotlib.font_manager
from sklearn import svm

In [340]:
clf = svm.OneClassSVM()
clf.fit(x_train_1)
y_pred_train = clf.predict(x_train_1)
y_pred_test = clf.predict(x_test_1)
# 실행시간 2m 4.7s

In [343]:
cf = confusion_matrix(y_train["positive"],y_predict)

In [349]:

print(cf)
print(classification_report(y_train, y_pred_train))
print("-------------------------------------------------------")
print(classification_report(y_test, y_pred_test))

[[   0    0    0]
 [ 217    0 2782]
 [ 131    0  370]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00      2999
           1       0.04      0.15      0.07       501

    accuracy                           0.02      3500
   macro avg       0.01      0.05      0.02      3500
weighted avg       0.01      0.02      0.01      3500

-------------------------------------------------------
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00      1285
           1       0.13      0.23      0.16       215

    accuracy                           0.03      1500
   macro avg       0.04      0.08      0.05      1500
weighted avg       0.02      0.03      0.02      1500



/home/shkim/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/shkim/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/shkim/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/shkim/.local/lib/python3.8/site-packages/skle